econometrics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 45.9.27.162
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: econometrics
      schema: public
      sslmode: disable 