version: 2

models:
  - name: ots_all
    description: "Aggregated OTS metrics per ID."
    columns:
      - name: id
        description: "Unique identifier."
        tests:
          - not_null
          - unique
      - name: ots_all_value
        description: "Sum of all OTS metrics."

  - name: blogger_ots
    description: "Calculated blogger OTS per ID."
    columns:
      - name: id
        description: "Unique identifier."
        tests:
          - not_null
          - unique
      - name: channel
        meta:
          dimension:
            type: string
      - name: blogger_ots
        description: "Blogger OTS metric."
